info:
  component: Importer !

spring.profiles.active: dev

management.security.enabled: false

security:
  basic.enabled: false
  user:
    name: admin
    password: admin

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    io.skalogs: INFO
    org.apache.http: DEBUG

management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: health,metrics,info,prometheus
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
---
spring.profiles: dev

process.urlRegistry: "http://localhost:8090"
process.frequency: 5
process.portClient: "8080"

validator.maxFields: 100
validator.maxSize: 20000
validator.maximumInThePastAllowed: 1
validator.maximumInTheFutureAllowed: 1
validator.mandatoryFields:
- "@timestamp"
- "project"
- "type"
- "project"
validator.blacklistType:
- "auditd"
- "kernel"
validator.whitelistType:
validator.cardinalityFieldChecks:

elasticsearch.host: localhost
elasticsearch.port: 9200
elasticsearch.clusterName: docker-cluster
elasticsearch.serviceElasticsearchUsername: elastic
elasticsearch.serviceElasticsearchPassword: changeme
elasticsearch.customIndexPrefix: "index-dev"

kafka.topic: processtopic
kafka.bootstrapServers: localhost:9092
kafka.pollingTime: 1000
kafka.pollRecord: 50
kafka.groupId: importer

spring.mail.host: ""
spring.mail.port: 25

snmp.community: Public
snmp.trapOid: .1.3.6.1.2.1.1.6
snmp.ipAddress: 127.0.0.1
snmp.port: 162

registry.active: true